# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20

# Missing top level class documentation comment.
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
