default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  user: postgres
  password: postgres

development:
  <<: *default
  database: liblog_development
  host: 127.0.0.1
  user: postgres
  password: postgres

test:
  <<: *default
  database: liblog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
